---
ReportDefinitions:
  - reportName: CHBDailyRegisterReport
    decryptionPathId: TradeLicenseDailyCollectionReport
    summary: CHB Daily Register Report
    version: 1.0.0
    moduleName: rainmaker-CHB
    sourceColumns:
      - name: applicant_name
        label: rainmaker.CHB.name
        type: string
        source: CHB
        total: false
      - name: applicant_mobile_no
        label: rainmaker.CHB.applicant_mobile_no
        type: string
        source: CHB
        total: false  
      - name: community_hall_code
        label: rainmaker.CHB.community_hall_code
        type: string
        source: CHB
        total: false
        isLocalisationRequired: true
      - name: booking_no
        label: rainmaker.CHB.booking_no
        type: string
        source: CHB
        total: false
      - name: amountpaid
        label: rainmaker.CHB.amountpaid
        type: string
        source: CHB
        total: true
      - name: booking_date
        label: rainmaker.CHB.booking_date
        type: string
        source: CHB
        total: false
      - name: status
        label: rainmaker.CHB.status
        type: string
        source: CHB
        total: false  
      - name: createdtime
        label: raimaker.CHB.createdtime
        type: string
        source: CHB
        showColumn: false
    searchParams:
      - name: booking_no
        label: rainmaker.CHB.booking_no
        type: string
        source: CHB
        isMandatory: false
        searchClause: AND b.booking_no = $booking_no
      - name: fromDate
        label: rainmaker.CHB.fromDate
        type: epoch
        source: CHB
        isMandatory: true
        searchClause: AND b.createdtime >= $fromDate
      - name: toDate
        label: rainmaker.CHB.toDate
        type: epoch
        source: CHB
        isMandatory: true
        searchClause: AND b.createdtime <= $toDate
    query: >
      select a.applicant_name as applicant_name,
      a.applicant_mobile_no as applicant_mobile_no,
      b.community_hall_code as community_hall_code,
      b.createdtime as createdtime,
      b.booking_no as booking_no,
      p.amountpaid as amountpaid,
      h.booking_date as booking_date,
      h.status as status
      from eg_chb_applicant_detail a, eg_chb_booking_detail b, egcl_paymentdetail p, eg_chb_slot_detail h
      where a.booking_id=b.booking_id and b.receipt_no=p.receiptnumber and b.booking_id=h.booking_id
      and 1=1
  - reportName: CHBRefundReport
    decryptionPathId: TradeLicenseDailyCollectionReport
    summary: CHB Refund Report
    version: 1.0.0
    moduleName: rainmaker-CHB
    sourceColumns:
      - name: applicant_name
        label: rainmaker.CHB.name
        type: string
        source: CHB
        total: false
      - name: applicant_mobile_no
        label: rainmaker.CHB.applicant_mobile_no
        type: string
        source: CHB
        total: false  
      - name: community_hall_code
        label: rainmaker.CHB.community_hall_code
        type: string
        source: CHB
        total: false
        isLocalisationRequired: true
      - name: booking_no
        label: rainmaker.CHB.booking_no
        type: string
        source: CHB
        total: false
      - name: amountpaid
        label: rainmaker.CHB.amountpaid
        type: string
        source: CHB
        total: true
      - name: booking_date
        label: rainmaker.CHB.booking_date
        type: string
        source: CHB
        total: false
      - name: status
        label: rainmaker.CHB.status
        type: string
        source: CHB
        total: false  
      - name: createdtime
        label: rainmaker.CHB.createdtime
        type: string
        source: CHB
        showColumn: false
    searchParams:
      - name: booking_no
        label: rainmaker.CHB.booking_no
        type: string
        source: CHB
        isMandatory: false
        searchClause: AND b.booking_no = $booking_no
      - name: fromDate
        label: rainmaker.CHB.fromDate
        type: epoch
        source: CHB
        isMandatory: true
        searchClause: AND b.createdtime >= $fromDate
      - name: toDate
        label: rainmaker.CHB.toDate
        type: epoch
        source: CHB
        isMandatory: true
        searchClause: AND b.createdtime <= $toDate
    query: >
      select a.applicant_name as applicant_name,
      a.applicant_mobile_no as applicant_mobile_no,
      b.community_hall_code as community_hall_code,
      b.createdtime as createdtime,
      b.booking_no as booking_no,
      p.amountpaid as amountpaid,
      h.booking_date as booking_date,
      h.status as status
      from eg_chb_applicant_detail a, eg_chb_booking_detail b, egcl_paymentdetail p, eg_chb_slot_detail h
      where a.booking_id=b.booking_id and b.receipt_no=p.receiptnumber and b.booking_id=h.booking_id and h.status='REFUNDAPPROVED'
      and 1=1
