serviceMaps:
  serviceName: asset-services
  mappings:
    - version: 1.0
      description: Persists asset details in eg_asset_assetdetails table
      fromTopic: save-asset-assetdetails
      isTransaction: true
      queryMaps:
        - query: INSERT INTO eg_asset_assetdetails (
                        id,
                        tenantId, 
                        bookRefNo, 
                        name, 
                        description, 
                        classification, 
                        parentCategory,
                        category,
                        subcategory,
                        department, 
                        applicationNo,
                        approvalNo, 
                        approvalDate, 
                        applicationDate, 
                        status, 
                        additionalDetails,
                        createdBy,
                        lastmodifiedBy, 
                        createdTime, 
                        lastmodifiedTime,
                        accountId,
                        financialYear,
                        sourceOfFinance,
                        invoiceDate,
                        invoiceNumber,
                        purchaseDate,
                        purchaseOrderNumber,
                        location,
                        purchaseCost,
                        acquisitionCost,
                        bookValue,
                        lifeofasset,
                        modeofpossessionoracquisition,
                        assetType,
                        assetUsage,
                        assetStatus
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: Asset
          jsonMaps:
            - jsonPath: $.Asset.id
            - jsonPath: $.Asset.tenantId
            - jsonPath: $.Asset.assetBookRefNo
            - jsonPath: $.Asset.assetName
            - jsonPath: $.Asset.description
            - jsonPath: $.Asset.assetClassification
            - jsonPath: $.Asset.assetParentCategory
            - jsonPath: $.Asset.assetCategory
            - jsonPath: $.Asset.assetSubCategory
            - jsonPath: $.Asset.department
            - jsonPath: $.Asset.applicationNo
            - jsonPath: $.Asset.approvalNo
            - jsonPath: $.Asset.approvalDate
            - jsonPath: $.Asset.applicationDate
            - jsonPath: $.Asset.status
            - jsonPath: $.Asset.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.Asset.auditDetails.createdBy
            - jsonPath: $.Asset.auditDetails.lastModifiedBy
            - jsonPath: $.Asset.auditDetails.createdTime
            - jsonPath: $.Asset.auditDetails.lastModifiedTime
            - jsonPath: $.Asset.accountId
            - jsonPath: $.Asset.financialYear
            - jsonPath: $.Asset.sourceOfFinance
            - jsonPath: $.Asset.invoiceDate
            - jsonPath: $.Asset.invoiceNumber
            - jsonPath: $.Asset.purchaseDate
            - jsonPath: $.Asset.purchaseOrderNumber
            - jsonPath: $.Asset.location
            - jsonPath: $.Asset.purchaseCost
            - jsonPath: $.Asset.acquisitionCost
            - jsonPath: $.Asset.bookValue
            - jsonPath: $.Asset.lifeofasset
            - jsonPath: $.Asset.modeofpossessionoracquisition
            - jsonPath: $.Asset.assetType
            - jsonPath: $.Asset.assetUsage
            - jsonPath: $.Asset.assetStatus


        - query: INSERT INTO eg_asset_document(documentId, documenttype, fileStoreId, assetid, documentuid, docDetails, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: Asset.documents.*
          jsonMaps:
            - jsonPath: $.Asset.documents.*.documentId
            - jsonPath: $.Asset.documents.*.documentType
            - jsonPath: $.Asset.documents.*.fileStoreId
            - jsonPath: $.Asset.id
            - jsonPath: $.Asset.documents.*.documentUid
            - jsonPath: $.Asset.documents.*.docDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.Asset.auditDetails.createdBy
            - jsonPath: $.Asset.auditDetails.lastModifiedBy
            - jsonPath: $.Asset.auditDetails.createdTime
            - jsonPath: $.Asset.auditDetails.lastModifiedTime

        - query: INSERT INTO eg_asset_addressDetails (
                  addressId,
                  tenantId,
                  doorNo,
                  latitude,
                  longitude,
                  addressNumber,
                  type,
                  addressLine1,
                  addressLine2,
                  landmark,
                  city,
                  pincode,
                  detail,
                  buildingName,
                  street,
                  locality_code,
                  locality_name,
                  locality_label,
                  locality_latitude,
                  locality_longitude,
                  locality_materializedPath,
                  asset_id
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: Asset.addressDetails
          jsonMaps:
            - jsonPath: $.Asset.addressDetails.addressId
            - jsonPath: $.Asset.tenantId
            - jsonPath: $.Asset.addressDetails.doorNo
            - jsonPath: $.Asset.addressDetails.latitude
            - jsonPath: $.Asset.addressDetails.longitude
            - jsonPath: $.Asset.addressDetails.addressNumber
            - jsonPath: $.Asset.addressDetails.type
            - jsonPath: $.Asset.addressDetails.addressLine1
            - jsonPath: $.Asset.addressDetails.addressLine2
            - jsonPath: $.Asset.addressDetails.landmark
            - jsonPath: $.Asset.addressDetails.city
            - jsonPath: $.Asset.addressDetails.pincode
            - jsonPath: $.Asset.addressDetails.detail
            - jsonPath: $.Asset.addressDetails.buildingName
            - jsonPath: $.Asset.addressDetails.street
            - jsonPath: $.Asset.addressDetails.locality.code
            - jsonPath: $.Asset.addressDetails.locality.name
            - jsonPath: $.Asset.addressDetails.locality.label
            - jsonPath: $.Asset.addressDetails.locality.latitude
            - jsonPath: $.Asset.addressDetails.locality.longitude
            - jsonPath: $.Asset.addressDetails.locality.materializedPath
            - jsonPath: $.Asset.id

        - query: INSERT INTO eg_asset_auditdetails SELECT * FROM eg_asset_assetdetails WHERE id = ?;
          basePath: Asset
          jsonMaps:
            - jsonPath: $.Asset.id


    - version: 1.0
      description: update assetdetails details in EG_Asset_assetdetails table
      fromTopic: update-asset-assetdetails
      isTransaction: true
      queryMaps:
        - query:  UPDATE eg_asset_assetdetails 
                  SET 
                    bookrefno = ?, 
                    name = ?, 
                    description = ?, 
                    classification = ?, 
                    parentCategory = ?, 
                    category = ?, 
                    subcategory = ?, 
                    department = ?, 
                    applicationno = ?, 
                    approvalNo = ?, 
                    applicationDate = ?, 
                    status = ?, 
                    additionaldetails = ?, 
                    lastmodifiedby = ?, 
                    lastmodifiedtime = ?, 
                    approvalDate = ?, 
                    accountId = ?, 
                    financialYear = ?, 
                    sourceOfFinance = ?,
                    invoiceDate = ?,
                    invoiceNumber = ?,
                    purchaseDate = ?,
                    purchaseOrderNumber = ?,
                    location = ?,
                    purchaseCost = ?,
                    acquisitionCost = ?,
                    bookValue = ?,
                    lifeofasset = ?,
                    modeofpossessionoracquisition = ?,
                    assetType = ?,
                    assetUsage = ?,
                    assetStatus = ?
                  WHERE id = ?;
          basePath: Asset
          jsonMaps:
            - jsonPath: $.Asset.assetBookRefNo
            - jsonPath: $.Asset.assetName
            - jsonPath: $.Asset.description
            - jsonPath: $.Asset.assetClassification
            - jsonPath: $.Asset.assetParentCategory
            - jsonPath: $.Asset.assetCategory
            - jsonPath: $.Asset.assetSubCategory
            - jsonPath: $.Asset.department
            - jsonPath: $.Asset.applicationNo
            - jsonPath: $.Asset.approvalNo
            - jsonPath: $.Asset.approvalDate
            - jsonPath: $.Asset.status
            - jsonPath: $.Asset.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.Asset.auditDetails.lastModifiedBy
            - jsonPath: $.Asset.auditDetails.lastModifiedTime
            - jsonPath: $.Asset.approvalDate
            - jsonPath: $.Asset.accountId
            - jsonPath: $.Asset.financialYear
            - jsonPath: $.Asset.sourceOfFinance
            - jsonPath: $.Asset.invoiceDate
            - jsonPath: $.Asset.invoiceNumber
            - jsonPath: $.Asset.purchaseDate
            - jsonPath: $.Asset.purchaseOrderNumber
            - jsonPath: $.Asset.location
            - jsonPath: $.Asset.purchaseCost
            - jsonPath: $.Asset.acquisitionCost
            - jsonPath: $.Asset.bookValue
            - jsonPath: $.Asset.lifeofasset
            - jsonPath: $.Asset.modeofpossessionoracquisition
            - jsonPath: $.Asset.assetType
            - jsonPath: $.Asset.assetUsage
            - jsonPath: $.Asset.assetStatus
            - jsonPath: $.Asset.id

        - query: INSERT INTO eg_asset_auditdetails SELECT * FROM eg_asset_assetdetails WHERE id = ?;
          basePath: Asset
          jsonMaps:
            - jsonPath: $.Asset.id

        - query: INSERT INTO eg_asset_document(documentid, documenttype, filestoreid, assetid, documentuid, docdetails, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (documentid) DO UPDATE SET documenttype =?,  fileStoreId =?, docDetails=?, lastmodifiedby =?, lastmodifiedtime =?;
          basePath: Asset.documents.*
          jsonMaps:
            - jsonPath: $.Asset.documents.*.documentId
            - jsonPath: $.Asset.documents.*.documentType
            - jsonPath: $.Asset.documents.*.fileStoreId
            - jsonPath: $.Asset.id
            - jsonPath: $.Asset.documents.*.documentUid
            - jsonPath: $.Asset.documents.*.docDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.Asset.auditDetails.createdBy
            - jsonPath: $.Asset.auditDetails.lastModifiedBy
            - jsonPath: $.Asset.auditDetails.createdTime
            - jsonPath: $.Asset.auditDetails.lastModifiedTime

    - version: 1.0
      description: save assignment details in EG_Asset_assignmentdetails table
      fromTopic: save-asset-assignmentdetails
      isTransaction: true
      queryMaps:
        - query:  INSERT INTO eg_asset_assignmentdetails(
                  assignmentid,
                  tenantid,
                  assetid,
                  applicationno,
                  assignedusername,
                  designation,
                  department,
                  assigneddate,
                  returnDate,
                  createdby,
                  lastModifiedby,
                  createdtime,
                  lastModifiedtime,
                  isassigned,
                  employeecode
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
               ON CONFLICT (assetid) 
               DO UPDATE SET
                  assignmentid = EXCLUDED.assignmentid,
                  tenantid = EXCLUDED.tenantid,
                  applicationno = EXCLUDED.applicationno,
                  assignedusername = EXCLUDED.assignedusername,
                  employeecode = EXCLUDED.employeecode,
                  designation = EXCLUDED.designation,
                  department = EXCLUDED.department,
                  assigneddate = EXCLUDED.assigneddate,
                  returnDate = EXCLUDED.returnDate,
                  createdby = EXCLUDED.createdby,
                  lastModifiedby = EXCLUDED.lastModifiedby,
                  createdtime = EXCLUDED.createdtime,
                  lastModifiedtime = EXCLUDED.lastModifiedtime,
                  isassigned = EXCLUDED.isassigned;
          basePath: Asset.assetAssignment
          jsonMaps:
            - jsonPath: $.Asset.assetAssignment.assignmentId
            - jsonPath: $.Asset.tenantId
            - jsonPath: $.Asset.id
            - jsonPath: $.Asset.applicationNo
            - jsonPath: $.Asset.assetAssignment.assignedUserName
            - jsonPath: $.Asset.assetAssignment.designation
            - jsonPath: $.Asset.assetAssignment.department
            - jsonPath: $.Asset.assetAssignment.assignedDate
            - jsonPath: $.Asset.assetAssignment.returnDate
            - jsonPath: $.Asset.assetAssignment.auditDetails.createdBy
            - jsonPath: $.Asset.assetAssignment.auditDetails.lastModifiedBy
            - jsonPath: $.Asset.assetAssignment.auditDetails.createdTime
            - jsonPath: $.Asset.assetAssignment.auditDetails.lastModifiedTime
            - jsonPath: $.Asset.assetAssignment.isAssigned
            - jsonPath: $.Asset.assetAssignment.employeeCode

    
    - version: 1.0
      description: update assignment details in eg_asset_assignmentdetails table
      fromTopic: update-asset-assignmentdetails
      isTransaction: true
      queryMaps:
        - query:  UPDATE eg_asset_assignmentdetails
                  SET
                    assignedusername = ?,
                    employeecode = ?,
                    designation = ?,
                    department = ?,
                    returndate = ?,
                    lastmodifiedby = ?,
                    lastmodifiedtime = ?,
                    isassigned = ?
                  WHERE
                    assignmentid = ?;
          basePath: Asset.assetAssignment
          jsonMaps:
            - jsonPath: $.Asset.assetAssignment.assignedUserName
            - jsonPath: $.Asset.assetAssignment.employeeCode
            - jsonPath: $.Asset.assetAssignment.designation
            - jsonPath: $.Asset.assetAssignment.department
            - jsonPath: $.Asset.assetAssignment.returnDate
            - jsonPath: $.Asset.assetAssignment.auditDetails.lastModifiedBy
            - jsonPath: $.Asset.assetAssignment.auditDetails.lastModifiedTime
            - jsonPath: $.Asset.assetAssignment.isAssigned
            - jsonPath: $.Asset.assetAssignment.assignmentId

        - query: INSERT INTO eg_asset_assignment_history SELECT * FROM EG_Asset_assignmentdetails WHERE assignmentid = ?;
          basePath: Asset
          jsonMaps:
            - jsonPath: $.Asset.assetAssignment.assignmentId
