serviceMaps:
  serviceName: cnd-service
  mappings:
    - version: 1.0
      description: Persists C&D waste application details
      fromTopic: save-cnd-application
      isTransaction: true
      queryMaps:
        - query: INSERT INTO public.ug_cnd_application_details(application_id, tenant_id, application_number, application_type, vehicle_type, type_of_construction, deposit_centre_details, applicant_detail_id, address_detail_id, applicant_mobile_number, requested_pickup_date, application_status, additional_details, house_area, construction_from_date, construction_to_date, property_type, total_waste_quantity, no_of_trips, vehicle_id, vendor_id, pickup_date, completed_on, created_by, created_time, last_modified_by, last_modified_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?::DATE, ?, ?, ?,  ?::DATE,  ?::DATE, ?, ?, ?, ?, ?,  ?::DATE, ?::TIMESTAMP, ?, ?, ?, ?);
          basePath: cndApplication
          jsonMaps:
            - jsonPath: $.cndApplication.applicationId
            - jsonPath: $.cndApplication.tenantId
            - jsonPath: $.cndApplication.applicationNumber
            - jsonPath: $.cndApplication.applicationType
            - jsonPath: $.cndApplication.vehicleType
            - jsonPath: $.cndApplication.typeOfConstruction
            - jsonPath: $.cndApplication.depositCentreDetails
            - jsonPath: $.cndApplication.applicantDetailId
            - jsonPath: $.cndApplication.addressDetailId
            - jsonPath: $.cndApplication.applicantMobileNumber
            - jsonPath: $.cndApplication.requestedPickupDate
            - jsonPath: $.cndApplication.applicationStatus
            - jsonPath: $.cndApplication.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.cndApplication.houseArea
            - jsonPath: $.cndApplication.constructionFromDate
            - jsonPath: $.cndApplication.constructionToDate
            - jsonPath: $.cndApplication.propertyType
            - jsonPath: $.cndApplication.totalWasteQuantity
            - jsonPath: $.cndApplication.noOfTrips
            - jsonPath: $.cndApplication.vehicleId
            - jsonPath: $.cndApplication.vendorId
            - jsonPath: $.cndApplication.pickupDate
            - jsonPath: $.cndApplication.completedOn
            - jsonPath: $.cndApplication.auditDetails.createdBy
            - jsonPath: $.cndApplication.auditDetails.createdTime
            - jsonPath: $.cndApplication.auditDetails.lastModifiedBy
            - jsonPath: $.cndApplication.auditDetails.lastModifiedTime

        - query: INSERT INTO public.ug_cnd_waste_detail(waste_type_id, application_id, quantity, metrics, entered_by_user_type, waste_type, created_by, created_time, last_modified_by, last_modified_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: cndApplication.wasteTypeDetails.*
          jsonMaps:
            - jsonPath: $.cndApplication.wasteTypeDetails.*.wasteTypeId
            - jsonPath: $.cndApplication.applicationId
            - jsonPath: $.cndApplication.wasteTypeDetails.*.quantity
            - jsonPath: $.cndApplication.wasteTypeDetails.*.metrics
            - jsonPath: $.cndApplication.wasteTypeDetails.*.enteredByUserType
            - jsonPath: $.cndApplication.wasteTypeDetails.*.wasteType
            - jsonPath: $.cndApplication.auditDetails.createdBy
            - jsonPath: $.cndApplication.auditDetails.createdTime
            - jsonPath: $.cndApplication.auditDetails.lastModifiedBy
            - jsonPath: $.cndApplication.auditDetails.lastModifiedTime

        - query: INSERT INTO public.ug_cnd_document_detail(document_detail_id, application_id, document_type, uploaded_by_user_type, file_store_id, created_by, created_time, last_modified_by, last_modified_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: cndApplication.documentDetails.*
          jsonMaps:
            - jsonPath: $.cndApplication.documentDetails.*.documentDetailId
            - jsonPath: $.cndApplication.applicationId
            - jsonPath: $.cndApplication.documentDetails.*.documentType
            - jsonPath: $.cndApplication.documentDetails.*.uploadedByUserType
            - jsonPath: $.cndApplication.documentDetails.*.fileStoreId
            - jsonPath: $.cndApplication.auditDetails.createdBy
            - jsonPath: $.cndApplication.auditDetails.createdTime
            - jsonPath: $.cndApplication.auditDetails.lastModifiedBy
            - jsonPath: $.cndApplication.auditDetails.lastModifiedTime

    - version: 1.0
      description: Update CND application detail
      fromTopic: update-cnd-application
      isTransaction: true
      queryMaps:
        - query: UPDATE public.ug_cnd_application_details SET tenant_id = ?, application_type = ?, vehicle_type = ?, type_of_construction = ?, deposit_centre_details = ?, applicant_detail_id = ?, requested_pickup_date = ?::DATE, application_status = ?, additional_details = ?, house_area = ?, construction_from_date = ?::DATE, construction_to_date = ?::DATE, property_type = ?, total_waste_quantity = ?, no_of_trips = ?, vehicle_id = ?, vendor_id = ?, pickup_date = ?::DATE, completed_on = ?::TIMESTAMP, last_modified_by = ?, last_modified_time = ? WHERE application_id = ?;
          basePath: cndApplication
          jsonMaps:
            - jsonPath: $.cndApplication.tenantId
            - jsonPath: $.cndApplication.applicationType
            - jsonPath: $.cndApplication.vehicleType
            - jsonPath: $.cndApplication.typeOfConstruction
            - jsonPath: $.cndApplication.depositCentreDetails
            - jsonPath: $.cndApplication.applicantDetailId
            - jsonPath: $.cndApplication.requestedPickupDate
            - jsonPath: $.cndApplication.applicationStatus
            - jsonPath: $.cndApplication.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.cndApplication.houseArea
            - jsonPath: $.cndApplication.constructionFromDate
            - jsonPath: $.cndApplication.constructionToDate
            - jsonPath: $.cndApplication.propertyType
            - jsonPath: $.cndApplication.totalWasteQuantity
            - jsonPath: $.cndApplication.noOfTrips
            - jsonPath: $.cndApplication.vehicleId
            - jsonPath: $.cndApplication.vendorId
            - jsonPath: $.cndApplication.pickupDate
            - jsonPath: $.cndApplication.completedOn
            - jsonPath: $.cndApplication.auditDetails.lastModifiedBy
            - jsonPath: $.cndApplication.auditDetails.lastModifiedTime
            - jsonPath: $.cndApplication.applicationId