SearchDefinitions:
  moduleName: asset-services
  summary: Asset Services Inbox API
  version: 1.0.0
  definitions:
    - name: inboxassetsearch
      query:
        baseQuery: Select row_to_json(result) from
          (
          select DISTINCT(asset.applicationNo),pi.createdtime from eg_asset_assetdetails as asset
          INNER JOIN eg_asset_addressDetails asset_add ON asset_add.asset_id = asset.id
          INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = asset.applicationNo
          LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
          $where
          AND pi.createdtime IN (select max(createdtime) from eg_wf_processinstance_v2 wf where wf.businessid = asset.applicationNo GROUP BY wf.businessid)
          order by pi.createdtime asc $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: asset.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: asset.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: asset.applicationNo
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNo
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset

      output:
        jsonFormat: {"ResponseInfo": {},"Asset": []}
        outJsonPath: $.Asset
        responseInfoPath: $.ResponseInfo

    - name: inboxassetsearchdesc
      query:
        baseQuery: Select row_to_json(result) from
           (
          select DISTINCT(asset.applicationNo),pi.createdtime from eg_asset_assetdetails as asset
          INNER JOIN eg_asset_addressDetails asset_add ON asset_add.asset_id = asset.asset_id
          INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = asset.applicationNo
          LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
          $where
          AND pi.createdtime IN (select max(createdtime) from eg_wf_processinstance_v2 wf where wf.businessid = asset.applicationNo GROUP BY wf.businessid)
          order by pi.createdtime desc $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: asset.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: asset.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: asset.applicationNo
            isMandatory: false
            jsonPath: $.searchCriteria.applicationNo
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset

      output:
        jsonFormat: {"ResponseInfo": {},"Asset": []}
        outJsonPath: $.Asset
        responseInfoPath: $.ResponseInfo