SearchDefinitions:
  moduleName: request-service.mobile_toilet
  summary: MT Service Inbox API
  version: 1.0.0
  definitions:
    - name: inboxMTSearch
      query:
        baseQuery: Select row_to_json(result) from
          (
          select DISTINCT(urmt.booking_no),pi.createdtime from 
          upyog_rs_mobile_toilet_booking_details as urmt
          INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = urmt.booking_no
          LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
          $where
          AND pi.createdtime IN (select max(createdtime) from eg_wf_processinstance_v2 wf where wf.businessid = urmt.booking_no GROUP BY wf.businessid)
          order by pi.createdtime asc $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: urmt.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset

      output:
        jsonFormat: {"ResponseInfo": {},"mobileToiletBookingDetails": []}
        outJsonPath: $.mobileToiletBookingDetails
        responseInfoPath: $.ResponseInfo
    - name: inboxMTSearchdesc
      query:
        baseQuery: Select row_to_json(result) from
          (
          select DISTINCT(urmt.booking_no),pi.createdtime from 
          upyog_rs_mobile_toilet_booking_details as urmt
          INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = urmt.booking_no
          LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
          $where
          AND pi.createdtime IN (select max(createdtime) from eg_wf_processinstance_v2 wf where wf.businessid = urmt.booking_no GROUP BY wf.businessid)
          order by pi.createdtime desc $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: urmt.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset

      output:
        jsonFormat: {"ResponseInfo": {},"mobileToiletBookingDetails": []}
        outJsonPath: $.mobileToiletBookingDetails
        responseInfoPath: $.ResponseInfo